extend = ".ruff-base.toml"

exclude = [
    "experiments",
    "scraps",
    "**/src/comic-utils/src/comic_utils/pyarmor_runtime_000000/*",
    "**/src/comic-utils/src/comic_utils/get_panel_bytes.py",
    "**/src/comic-utils/src/comic_utils/cpi*",
]

[lint]
ignore = [
    "PLR0913",
    "TD002",
]

[lint.per-file-ignores]
"scripts/*" = ["INP001"]
