line-length = 100

exclude = [
        "scraps",
    ]

[lint]
    select = ["ALL"]

    ignore = [
        "D100", "D101", "D102", "D103", "D107", "D203", "D213",
        "C901", "PLR0912",
        "COM812",
        "FBT001", "FBT002",
        "FIX002",
        "LOG015", "G004",
        "PLR0913",
        "S101", "S311",
        "TD002", "TD003",
    ]

    exclude = [
        "scripts/actionbar_example.py",
        "scripts/scrolling_list.py",
        "scripts/test-logging.py",
        "scripts/test_comic_archive.py",
        "scripts/test_zip_kivy_loader.py",
        "src/barks-reader/src/barks_reader/open_zip_archive.py",
        "src/barks-reader/src/barks_reader/pyarmor_runtime_000000/*"
    ]

    [lint.per-file-ignores]
        "scripts/*" = ["INP001"]
