[environment]
python = "./.venv"
root = [
    ".",
    "./src/barks-reader/src",
    "./src/barks-build-comic-images/src",
    "./src/barks-fantagraphics/src",
    "./src/comic-utils/src",
]
extra-paths = [
    "./src/barks-reader/src",
    "./src/barks-build-comic-images/src",
    "./src/barks-fantagraphics/src",
    "./src/comic-utils/src",
]

[src]
exclude = [
  	"**/experiments",
   "**/scraps",
    "**/pyarmor_runtime_000000",
    "src/comic-utils/src/comic_utils/cpi_download.py",
    "src/comic-utils/src/comic_utils/cpi_models.py",
    "src/comic-utils/src/comic_utils/cpi_parsers.py",
]
