[environment]
python = "./.venv"
root = ["."]

[src]
exclude = [
  	"**/experiments",
   "**/scraps",
    "**/pyarmor_runtime_000000",
    "src/comic-utils/src/comic_utils/cpi_download.py",
    "src/comic-utils/src/comic_utils/cpi_models.py",
    "src/comic-utils/src/comic_utils/cpi_parsers.py",
]
